Vagrant.require_plugin('vagrant-1cloud')

Vagrant.configure('2') do |config|
  config.vm.define "test" do |t|
    t.vm.provider :onecloud do |provider, override|
      override.ssh.private_key_path = 'test_id_rsa'
      override.vm.box = 'onecloud'
      override.vm.hostname = 'test'
      override.vm.provision :shell, :path => 'scripts/provision.sh'

      provider.token = ENV['DO_TOKEN']
    end
  end
end